services:
  turbo-front:
    container_name: turbo-front
    image: node:20
    volumes:
      - .:/app
    ports:
      - ${QUASAR_PORT:-4200}:4200
    working_dir: /app
    command: sh -c 'npm install && npm run dev'
    environment:
      - API_KEY=${API_KEY}

  turbo-api:
    container_name: turbo-api
    image: node:20
    volumes:
      - .:/app
    ports:
      - ${API_PORT:-3069}:3069
    working_dir: /app
    command: sh -c 'cd api && node app.js'
