services:
  turbo-front:
    image: node:20
    volumes:
      - .:/app
    ports:
      - ${QUASAR_PORT:-4200}:4200
    working_dir: /app
    command: sh -c 'npm install && npm run dev'
    environment:
      - API_KEY=${API_KEY}

  # annuairebio_api:
  #   working_dir: /app
  #   image: node:18
  #   volumes:
  #     - ./backend:/app
  #   ports:
  #     - ${QUASAR_PORT:-9001}d:9001
  #   command: sh -c 'cd backend && node index.js'
